Create code
ingridesouza/Projeto_Python pull request #1
Opened 2023-10-27 13:24 UTC by smpguga

ideia

2023-10-30 23:08 UTC, ingridesouza reviewed
Envie novamente

2023-11-02 21:14 UTC, ingridesouza requested changes
Alterar o código, separando a comanda de cada mesa e de cada pessoa que estava presente nas respectivas mesas.

2023-11-03 12:38 UTC, smpguga commented
Feito!

2023-11-04 20:07 UTC, ingridesouza approved these changes

2023-11-04 20:08 UTC, ingridesouza approved these changes

2023-11-04 20:09 UTC, merged